# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marks', '0005_delete_skip'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterNotification',
            fields=[
                ('scheduledsubject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timetable.ScheduledSubject')),
                ('value', models.CharField(max_length=10)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.Student')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.Teacher')),
            ],
            bases=('timetable.scheduledsubject',),
        ),
    ]
