# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledsubject',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='subject date'),
        ),
    ]
