# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_skip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skip',
            name='value',
            field=models.BooleanField(default=True),
        ),
    ]
