# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0004_auto_20170905_2328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skip',
        ),
    ]
